### ISSUE TITLE
Currency conversion error

### ISSUE THREAD

**Issue by eofster** [fedoco/apple-slicer#2]
The script doesn’t seem to work for me for currencies other than EUR:

```
Apple Inc.
1 Infinite Loop
Cupertino, CA 95014
U.S.A.

Sales in United States (US)
    Quantity    Product Amount  Exchange Rate   Amount in EUR
Traceback (most recent call last):
  File "./slicer.py", line 206, in <module>
    print_sales_by_corporation(sales, currencies)
  File "./slicer.py", line 175, in print_sales_by_corporation
    exchange_rate, tax_factor = currency_data[country_currency]
KeyError: 'USD'
```

What can I do to help?

**Comment by fedoco** [comment]
@eofster Could you please provide me with your (anonymized) input files?

**Comment by fedoco** [comment]
@eofster Are you still there?

**Comment by eofster** [comment]
Sorry, didn’t have time to anonymize the reports yet.

**Comment by eofster** [comment]
Hmm, my `financial_report.csv` doesn’t seem to have the exchange rate. It only has 11 elements in each line, not 12 like the script expects.

```
['Region (Currency)', 'Units Sold', 'Balance', 'Earned', 'Input Tax', 'Adjustments', 'Withholding Tax', 'Total Owed', 'Proceeds', 'Bank Account Currency', ‘']
```

**Comment by eofster** [comment]
It seems that I have two kinds of `financial_report.csv` that differ from the one you have.

For some reason during last several months I had a purchase from India that was being carried forward each month without being paid. So each CSV from that period is different in three ways:
1. It has 13 elements in each line, not 12 like the script expects.
2. It has a Balance column at index 2, so all indices that are involved in the exchange rate calculations are shifted by 1.
3. The purchases being carried forward have an empty string in the Exchange Rate column.

```
['Region (Currency)', 'Units Sold', 'Balance', 'Earned', 'Pre-Tax Subtotal', 'Input Tax', 'Adjustments', 'Withholding Tax', 'Total Owed', 'Exchange Rate', 'Proceeds', 'Bank Account Currency', ‘']
```

However, in my last financial report that purchase from India was finally paid, but the report doesn’t have the Exchange Rate column at all.

```
['Region (Currency)', 'Units Sold', 'Balance', 'Earned', 'Input Tax', 'Adjustments', 'Withholding Tax', 'Total Owed', 'Proceeds', 'Bank Account Currency', ‘’]
```

**Comment by fedoco** [comment]
My guess is that the reports with the `'Balance'` column are those of pending months for which payments have not yet been processed. For example, if you download the reports of February or March right now these are still preliminary figures and it should therefore say so in the bottom line. My script isn't designed to work with estimates, as there is not much sense in filing invoices which rely on these numbers - I have now updated the script accordingly in 7c3d85f07e10333be24b61555caf6ea4c2c6cef1.

Regarding the reports with an empty `'Exchange Rate'` column or no such column at all:
Unfortunately, I cannot think of a fix for these as long as Apple doesn't deliver reliable data. Sadly, iTC's financial reports are a mess in general: I cannot even identify columns by their header names because they are localized depending on the user's language settings...
But what's irritating to me is that even those reports contain the `'Balance'` column. Can you confirm these are pending reports from February or March, too? If so, they probably will get updated with exchange rates once they are final and should work then.

Thanks for your time!

**Comment by fedoco** [comment]
Closing after 30 days of inactivity. Please open a new issue if the problem persists.

**Comment by eofster** [comment]
The report without the ‘Exchange Rate’ column was indeed a preliminary one. Later it got updated and the ‘Exchange Rate’ column appeared.

However, the report with the ‘Balance’ column is the final one. It seems to be a case when the earnings from some region were not paid out. I don’t know yet why it happens, I haven’t received the answer yet. But the fact is, this is a final report.

I’ve prepared an anonymized version. The numbers don’t match, but you can see the structure of the report. All fields that were empty in the original report are kept empty in the anonymized one. I also had to change the file extension to ‘txt’ in order to attach it here.

[financial_report.txt](https://github.com/fedoco/apple-slicer/files/231832/financial_report.txt)

**Comment by eofster** [comment]
I finally received a reply from Apple, why this can happen. There is a threshold of $1.00 equivalent for earnings in some (maybe all) countries. So even if your total threshold is high enough to be paid out, there is still a country threshold. In my case, earnings from India were below this amount and were carried forward every month. This led to a different `financial_report.txt` column count with the Balance column present.

**Comment by fedoco** [comment]
Thanks for your follow-up regarding this issue! It seems to me that I can address this by simply ignoring the `Balance` column if it's there. I addition, the script needs to ignore all lines below the second occurrence of a header line (if there is any) because to my understanding, earnings listed below the second header aren't payed out yet and therefore shouldn't affect the total earnings. Do you agree?

**Comment by eofster** [comment]
I agree.
